dataset: CIFAR10
# res: 64
# subset: imagenette
# model: ConvNetD4
device: [3]

ipc: 10
syn_steps: 80
expert_epochs: 2
zca: False
lr_img: 100
lr_teacher: 0.01
buffer_path: /home/guoziyao/Gzy/FTD-distillation/buffer_storage/ipc50
data_path: /home/guoziyao/Gzy/FTD-distillation/dataset
ema_decay: 0.9995
Iteration: 10000
batch_syn: 500

# wandb
project: trash

num_eval: 1
eval_it: 500
skip_first_eva: True

lr_y: 10.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
learn_end_epoch: 1000
batch_train: 128
min_start_epoch: 0
Initial_Step: 10
max_start_epoch: 20
lr_lr: 0.00001
zca: True

