dataset: CIFAR100
ipc: 10
syn_steps: 20
expert_epochs: 2
zca: true
lr_img: 100
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset/
ema_decay: 0.9995
Iteration: 10000

# wandb
project: CIFAR100_ipc10

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 2.0
Momentum_y: 0.9
threshold: 1.0
pix_init: samples_predicted_correctly
learn_end_epoch: 3000
batch_train: 128
min_start_epoch: 10
Initial_Step: 30
max_start_epoch: 40

