dataset: Tiny
res: 64
model: ConvNetD4
device: [0,1,2,3]

ipc: 50
syn_steps: 20
expert_epochs: 2
lr_img: 100
lr_teacher: 0.01
buffer_path: /home/guoziyao/Gzy/FTD-distillation/buffer_storage/256b_100epoch
data_path: /home/guoziyao/Gzy/FTD-distillation/dataset/tiny-imagenet-200
ema_decay: 0.995
Iteration: 10000
batch_syn: 1000

# wandb
project: Tiny_ipc50

num_eval: 1
eval_it: 500
skip_first_eva: True

lr_y: 10.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
learn_end_epoch: 1
batch_train: 128
min_start_epoch: 40
Initial_Step: 46
max_start_epoch: 60
lr_lr: 0.0001

zca: True

