dataset: CIFAR10
# res: 64
# subset: imagenette
model: ConvNetBN
device: [0,1,2,3]

ipc: 1000
syn_steps: 80
expert_epochs: 2
lr_img: 50
lr_teacher: 0.01

# buffer_path: ../buffer_storage/CIFAR10_ipc50
buffer_path: ../buffer_storage/256b_100epoch

data_path: /home/guoziyao/Gzy/FTD-distillation/dataset
ema_decay: 0.995
Iteration: 10000
batch_syn: 1000

# wandb
project: CIFAR10_ipc1000

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 10.
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
learn_end_epoch: 10
batch_train: 128
min_start_epoch: 40
Initial_Step: 46
max_start_epoch: 60
lr_lr: 0.00001
zca: True

eval_mode: C

Initialize_Label_With_Another_Model: True
Initialize_Label_Model: ConvNet
Initialize_Label_Model_Dir: ../buffer_storage/ipc50
