dataset: ImageNet
res: 128
subset: imagenette
model: ConvNetD5
device: [2]

ipc: 1
syn_steps: 20
expert_epochs: 2
zca: False
lr_img: 10000
lr_teacher: 0.001
buffer_path: ../buffer_storage/256BS
data_path: /home/guoziyao/Gzy/imagenet
ema_decay: 0.9995
Iteration: 10000

# wandb
project: imagenette_ipc1

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 1000.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
learn_end_epoch: 1
batch_train: 128
min_start_epoch: 0
Initial_Step: 8
max_start_epoch: 10
lr_lr: 0.000001

