dataset: ImageNet
res: 128
subset: imagenette
model: ConvNetD5
device: [0,1,2,3]

ipc: 200
syn_steps: 60
expert_epochs: 2
zca: False
lr_img: 50
lr_teacher: 0.001
buffer_path: ../buffer_storage/256BS
data_path: /home/guoziyao/Gzy/imagenet
ema_decay: 0.995
Iteration: 10000
batch_syn: 100

# wandb
project: imagenette_ipc200

num_eval: 1
eval_it: 500
skip_first_eva: True
parall_eva: True

lr_y: 10.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
learn_end_epoch: 1
batch_train: 128
min_start_epoch: 30
Initial_Step: 36
max_start_epoch: 40
lr_lr: 0.000001

